# Generated by Django 2.1.7 on 2020-01-25 17:44

from django.db import migrations, models
import django.db.models.deletion
import face_recog_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imgs_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadToRecog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=face_recog_app.models.user_directory_path_for_to_predict)),
            ],
        ),
        migrations.CreateModel(
            name='LiveRecognizedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='RecognizesImages')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgs_upload.People')),
            ],
        ),
        migrations.CreateModel(
            name='RecogedImageUploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgs_upload.People')),
            ],
        ),
    ]
